name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'AI Expense Tracker/package-lock.json'

      - name: Install dependencies
        working-directory: ./AI Expense Tracker
        run: npm install

      - name: Build project
        working-directory: ./AI Expense Tracker
        run: npm run build

      - name: Deploy to Firebase Hosting
        working-directory: ./AI Expense Tracker
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"

